"use client";
import { useMemo } from "react";
import { ArrowLeft, Download, Printer } from "lucide-react";
export type MarksheetMark={subject:string;marks:number|null;max_marks:number;pass_percentage:number;status?:"marked"|"absent"|"fail"|"pass"};
export type MarksheetData={student:any;exam:any;marks:MarksheetMark[];org:any;settings:any};
const SCALE=[{min:90,grade:"A+",remark:"Outstanding"},{min:80,grade:"A",remark:"Excellent"},{min:70,grade:"B+",remark:"Very Good"},{min:60,grade:"B",remark:"Good"},{min:50,grade:"C",remark:"Satisfactory"},{min:33,grade:"D",remark:"Needs Improvement"},{min:0,grade:"F",remark:"Needs Improvement"}];
const fmt=(v?:string|null)=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})};
const grade=(p:number,s:any[])=>[...s].sort((a,b)=>b.min-a.min).find(x=>p>=x.min)||s[s.length-1];
const initials=(n:string)=>n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
function scaleOf(v:any){try{const p=typeof v==="string"?JSON.parse(v):v;if(!Array.isArray(p))return SCALE;const r=p.map((x:any)=>({min:Number(x.min??x.minimum??x.min_percentage),grade:String(x.grade??""),remark:String(x.remark??x.remarks??"")})).filter((x:any)=>Number.isFinite(x.min)&&x.grade);return r.length?r:SCALE}catch{return SCALE}}
export default function MarksheetTemplate({data,showToolbar=true}:{data:MarksheetData;showToolbar?:boolean}){
 const {student,exam,marks,org,settings}=data;const scale=useMemo(()=>scaleOf(settings?.grading_scale),[settings?.grading_scale]);const totals=useMemo(()=>{const total=marks.reduce((s,r)=>s+Number(r.marks??0),0),max=marks.reduce((s,r)=>s+Number(r.max_marks||0),0),percentage=max?total/max*100:0;const passed=marks.length>0&&marks.every(r=>{if(r.status==="absent"||r.status==="fail")return false;if(r.status==="pass"&&r.marks==null)return true;return r.max_marks?Number(r.marks??0)/Number(r.max_marks)*100>=Number(r.pass_percentage??30):false});return{total,max,percentage,overall:grade(percentage,scale),passed}},[marks,scale]);const primary=settings?.primary_color||"#0e4b43",accent=settings?.secondary_color||"#c5a15a",name=org?.name||"Institution Name",studentName=[student?.first_name,student?.last_name].filter(Boolean).join(" ")||"Student Name";
 return <main className="min-h-screen bg-[#e9ece8] px-2 py-4 sm:px-5 sm:py-6">{showToolbar&&<div className="no-print mx-auto mb-4 flex max-w-[820px] items-center justify-between"><button onClick={()=>history.back()} className="rounded-lg border bg-white px-3 py-2 text-sm"><ArrowLeft size={16} className="mr-1 inline"/>Back</button><div className="flex gap-2"><button onClick={()=>print()} className="rounded-lg px-4 py-2 text-sm font-semibold text-white" style={{backgroundColor:primary}}><Printer size={16} className="mr-1 inline"/>Print</button><button onClick={()=>print()} className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold"><Download size={16} className="mr-1 inline"/>Save PDF</button></div></div>}
 <article className="marksheet relative mx-auto min-h-[1123px] w-full max-w-[794px] overflow-hidden bg-[#fbfaf6] text-[#202522] shadow-[0_18px_60px_rgba(0,0,0,.16)]"><div className="absolute inset-y-0 left-0 w-[6px]" style={{backgroundColor:accent}}/><div className="absolute inset-y-0 right-0 w-[6px]" style={{backgroundColor:accent}}/><div className="relative px-7 py-7 sm:px-10 sm:py-8">
 <header className="border-b-[3px] pb-5" style={{borderColor:accent}}><div className="flex items-center gap-4"><div className="grid h-[82px] w-[82px] shrink-0 place-items-center overflow-hidden rounded-full border-[3px] bg-white" style={{borderColor:accent}}>{settings?.logo_signed?<img src={settings.logo_signed} className="h-full w-full object-contain p-2" alt="Institute logo"/>:<span className="text-xl font-black" style={{color:primary}}>{initials(name)}</span>}</div><div className="min-w-0 flex-1 text-center"><p className="text-[8px] font-semibold uppercase tracking-[0.38em]" style={{color:accent}}>Academic Excellence • Character • Discipline</p><h1 className="mt-1 text-[26px] font-black uppercase leading-none tracking-[0.035em] sm:text-[31px]" style={{color:primary}}>{name}</h1><p className="mt-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500">Official Academic Record</p><p className="mt-2 text-[10px] text-slate-500">{[settings?.address,settings?.phone,settings?.email].filter(Boolean).join("  •  ")}</p></div><div className="hidden w-[82px] sm:block"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full border" style={{borderColor:accent}}><span className="text-[8px] font-bold uppercase tracking-widest" style={{color:primary}}>Official<br/>Record</span></div></div></div><div className="mt-6 text-center"><p className="text-[9px] font-bold uppercase tracking-[0.4em]" style={{color:accent}}>Academic Examination</p><h2 className="mt-1 text-[24px] font-black uppercase tracking-[0.09em]" style={{color:primary}}>{settings?.marksheet_title||"Statement of Marks"}</h2><p className="mt-1 text-[12px] font-semibold text-slate-500">{exam?.name||"Examination"}{exam?.exam_date?" • "+fmt(exam.exam_date):""}</p></div></header>
 <section className="mt-5 rounded-xl border bg-white/70 p-4" style={{borderColor:accent+"66"}}><div className="grid grid-cols-[1fr_86px] gap-4"><div className="grid grid-cols-2 gap-x-5 gap-y-3 sm:grid-cols-4"><Info l="Student Name" v={studentName} b/><Info l="Admission No." v={student?.admission_no}/><Info l="Father / Guardian" v={student?.father_name||student?.guardian_name}/><Info l="Mother" v={student?.mother_name}/><Info l="Gender" v={student?.gender}/><Info l="Date of Birth" v={fmt(student?.date_of_birth)}/><Info l="Examination" v={exam?.name}/><Info l="Result" v={totals.passed?"PASS":"FAIL"} b/></div><div className="h-[104px] w-[86px] overflow-hidden rounded-lg border-2 bg-slate-100" style={{borderColor:accent}}>{student?.photo_signed?<img src={student.photo_signed} alt={studentName} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-[9px] font-bold uppercase tracking-widest text-slate-400">Photo</div>}</div></div></section>
 <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[0.32em]" style={{color:accent}}>Academic Performance</p><h3 className="mt-1 text-[17px] font-black uppercase tracking-wide" style={{color:primary}}>Subject-wise Assessment</h3></div><p className="text-[10px] font-semibold text-slate-400">{marks.length} {marks.length===1?"Subject":"Subjects"}</p></div><div className="overflow-hidden rounded-lg border"><table className="w-full border-collapse text-[11px] sm:text-[12px]"><thead><tr style={{backgroundColor:primary,color:"#fff"}}><th className="w-10 p-2.5">S.No.</th><th className="p-2.5 text-left">Subject</th><th className="p-2.5">Maximum</th><th className="p-2.5">Obtained</th><th className="p-2.5">Grade</th><th className="p-2.5">Remarks</th></tr></thead><tbody>{marks.map((r,i)=>{const p=r.max_marks?Number(r.marks??0)/r.max_marks*100:0,g=grade(p,scale),v=r.marks==null?(r.status||"—").toUpperCase():r.marks,gg=r.marks==null?(r.status==="pass"?"P":r.status==="absent"?"AB":r.status==="fail"?"F":"—"):g.grade;return <tr key={r.subject+i} className={i%2?"bg-white":"bg-[#f4f4ee]"}><td className="border-b p-2.5 text-center">{i+1}</td><td className="border-b p-2.5 font-semibold">{r.subject}</td><td className="border-b p-2.5 text-center">{r.max_marks}</td><td className="border-b p-2.5 text-center font-black" style={{color:r.status==="fail"||r.status==="absent"?"#b91c1c":primary}}>{v}</td><td className="border-b p-2.5 text-center font-black" style={{color:primary}}>{gg}</td><td className="border-b p-2.5 text-center text-[10px] text-slate-500">{g.remark}</td></tr>})}<tr style={{backgroundColor:accent+"28"}}><td colSpan={2} className="p-3 text-right font-black">Grand Total</td><td className="p-3 text-center font-black">{totals.max}</td><td className="p-3 text-center font-black" style={{color:primary}}>{totals.total}</td><td colSpan={2} className="p-3 text-center font-black" style={{color:primary}}>{totals.overall.grade}</td></tr></tbody></table></div></section>
 <section className="mt-5 grid grid-cols-3 overflow-hidden rounded-xl border"><Stat l="Percentage" v={totals.percentage.toFixed(2)+"%"} p={primary}/><Stat l="Overall Grade" v={totals.overall.grade} p={primary}/><Stat l="Final Result" v={totals.passed?"PASS":"FAIL"} p={primary}/></section>
 <section className="mt-5 grid gap-4 sm:grid-cols-[1fr_1.2fr]"><div className="rounded-xl border bg-white/70 p-4"><p className="text-[9px] font-black uppercase tracking-[0.25em]" style={{color:accent}}>Grading Scale</p><table className="mt-3 w-full text-[9px]"><tbody>{scale.map(r=><tr key={r.grade+r.min}><td>{r.min}% & above</td><td className="text-center font-black" style={{color:primary}}>{r.grade}</td><td className="text-right text-slate-500">{r.remark}</td></tr>)}</tbody></table></div><div className="rounded-xl border bg-white/70 p-4"><p className="text-[9px] font-black uppercase tracking-[0.25em]" style={{color:accent}}>Result Remarks</p><p className="mt-3 text-[12px] leading-5 text-slate-600">{totals.passed?"The student has successfully completed the examination with an overall grade of "+totals.overall.grade+".":"The student has not met the minimum passing requirement in this examination."}</p></div></section>
 <section className="mt-12 grid grid-cols-3 gap-5"><Sign t="Class Teacher"/><div className="text-center"><div className="mx-auto h-14 w-14 rounded-full border-2 border-dashed" style={{borderColor:accent}}/><p className="mt-2 border-t pt-2 text-[9px] font-bold uppercase text-slate-500">Institution Seal</p></div><Sign t={settings?.authorized_signatory||"Authorized Signatory"}/></section><footer className="mt-8 border-t pt-3 text-center text-[8px] text-slate-400">This is an official academic record issued by {name}.<br/>Generated through EduTechLab • Authentic institutional record</footer></div><div className="absolute bottom-0 left-0 h-10 w-full" style={{background:"linear-gradient(90deg,"+primary+","+accent+","+primary+")"}}/></article>
 <style jsx global>{`@media print{html,body{background:#fff!important}.no-print{display:none!important}.marksheet{width:210mm!important;height:297mm!important;max-width:none!important;margin:0!important;box-shadow:none!important;break-after:page;page-break-after:always}.marksheet:last-child{break-after:auto;page-break-after:auto}@page{size:A4;margin:0}*{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}}`}</style></main>
}
function Info({l,v,b=false}:{l:string;v?:string|null;b?:boolean}){return <div><p className="text-[8px] font-bold uppercase tracking-wider text-slate-400">{l}</p><p className={"mt-0.5 truncate text-[10px] "+(b?"font-black":"font-semibold")}>{v||"—"}</p></div>}
function Stat({l,v,p}:{l:string;v:string;p:string}){return <div className="p-3 text-center border-r last:border-0"><p className="text-[8px] font-black uppercase tracking-wider text-slate-400">{l}</p><p className="mt-1 text-[18px] font-black" style={{color:p}}>{l==="Final Result"?(v==="PASS"?"✓ PASS":"✕ FAIL"):v}</p></div>}
function Sign({t}:{t:string}){return <div className="pt-8 text-center"><div className="border-t border-slate-400"/><p className="mt-2 text-[9px] font-bold uppercase text-slate-500">{t}</p><p className="text-[8px] text-slate-400">Signature & Date</p></div>}