"use client";
import Link from "next/link";
import { ArrowRight, Check, GraduationCap, Users, WalletCards, ClipboardCheck, MessageCircle, ShieldCheck, BarChart3 } from "lucide-react";

const modules = [
  ["Admissions & Students","Digital admissions, student profiles, classes, sections and records.",GraduationCap],
  ["Attendance","Daily attendance with clear class-wise visibility and reports.",ClipboardCheck],
  ["Fees & Receipts","Track dues, collections, receipts and payment history.",WalletCards],
  ["Exams & Results","Create exams, enter marks and generate result records.",BarChart3],
  ["Staff & Permissions","Create staff accounts and control access module by module.",Users],
  ["Parent Communication","Keep parents informed with notices and important updates.",MessageCircle],
];

export default function Home(){
return <main className="min-h-screen bg-[#f7f9fc] text-slate-900">
<header className="sticky top-0 z-50 border-b border-slate-200/70 bg-white/90 backdrop-blur-xl">
<div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8 lg:px-10">
<Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-950 text-white shadow-lg"><GraduationCap size={20}/></span><span className="text-xl font-bold tracking-tight">EduTech<span className="text-blue-600">Lab</span></span></Link>
<nav className="hidden items-center gap-8 text-sm font-medium text-slate-500 md:flex"><a href="#features" className="hover:text-slate-950">Features</a><a href="#workflow" className="hover:text-slate-950">How it works</a><a href="#security" className="hover:text-slate-950">Security</a></nav>
<div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100 sm:inline-flex">Sign in</Link><Link href="/register" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-slate-900/10 hover:-translate-y-0.5">Register institute <ArrowRight size={15}/></Link></div>
</div></header>

<section className="relative overflow-hidden bg-white">
<div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_25%,rgba(59,130,246,.13),transparent_30%),radial-gradient(circle_at_15%_70%,rgba(14,165,233,.08),transparent_28%)]"/>
<div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-20 pt-16 sm:px-8 lg:grid-cols-[.95fr_1.05fr] lg:px-10 lg:pb-28 lg:pt-24">
<div>
<div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3.5 py-2 text-xs font-bold text-blue-700"><span className="h-2 w-2 rounded-full bg-blue-600"/> Built for schools, coaching institutes & madrasas</div>
<h1 className="max-w-3xl text-5xl font-bold leading-[1.02] tracking-[-.045em] text-slate-950 sm:text-6xl lg:text-[72px]">Run your entire institution from <span className="text-blue-600">one place.</span></h1>
<p className="mt-7 max-w-2xl text-base leading-8 text-slate-500 sm:text-lg">Admissions, students, teachers, attendance, fees, exams, results and parent communication — organized into one modern workspace.</p>
<div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-bold text-white shadow-xl shadow-blue-600/20 hover:bg-blue-700">Create your institution <ArrowRight size={17}/></Link><a href="#features" className="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Explore features</a></div>
<div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-slate-400"><span className="flex items-center gap-2"><Check size={14} className="text-blue-600"/> Separate institution workspace</span><span className="flex items-center gap-2"><Check size={14} className="text-blue-600"/> Role-based access</span><span className="flex items-center gap-2"><Check size={14} className="text-blue-600"/> Mobile friendly</span></div>
</div>
<div className="relative">
<div className="absolute -inset-5 rounded-[2rem] bg-blue-100/50 blur-3xl"/>
<div className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-950 p-3 shadow-2xl shadow-slate-900/15">
<img src="https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=85" alt="Modern education campus" className="h-[360px] w-full rounded-[1.5rem] object-cover opacity-75 sm:h-[430px]"/>
<div className="absolute inset-3 rounded-[1.5rem] bg-gradient-to-t from-slate-950/90 via-slate-950/10 to-transparent"/>
<div className="absolute bottom-8 left-8 right-8">
<div className="rounded-2xl border border-white/15 bg-white/95 p-5 shadow-2xl backdrop-blur">
<div className="flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Institution overview</p><p className="mt-1 text-lg font-bold text-slate-900">Good morning, Admin</p></div><span className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Dashboard</span></div>
<div className="mt-4 grid grid-cols-3 gap-2">{[["Students","428"],["Attendance","94.2%"],["Dues","₹64.5K"]].map(([a,b])=><div key={a} className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-medium text-slate-400">{a}</p><p className="mt-1 text-base font-bold text-slate-900">{b}</p></div>)}</div>
</div></div></div>
</div></div></section>

<section id="features" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10">
<div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Everything connected</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-5xl">The daily tools your team actually needs.</h2><p className="mt-5 text-base leading-7 text-slate-500">Replace scattered registers, spreadsheets and separate workflows with one structured system.</p></div>
<div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{modules.map(([title,copy,Icon])=><div key={title as string} className="group rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-900/5"><div className="grid h-12 w-12 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon size={21}/></div><h3 className="mt-6 text-lg font-bold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{copy as string}</p><div className="mt-6 flex items-center gap-1 text-xs font-bold text-blue-600 opacity-0 transition group-hover:opacity-100">Learn more <ArrowRight size={13}/></div></div>)}</div>
</section>

<section id="workflow" className="border-y border-slate-200 bg-white py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-14 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Simple workflow</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-5xl">From registration to daily operations.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-500">Each institution gets its own workspace. The institute owner becomes the main Admin and can create staff accounts with the permissions they need.</p><div className="mt-9 space-y-5">{[["01","Register your institute","Set up your institution profile and owner account."],["02","Configure your workspace","Create sessions, classes, sections, staff and permissions."],["03","Run everything from one dashboard","Manage students, attendance, fees, exams and communication."]].map(([n,t,c])=><div key={n} className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-slate-950 text-xs font-bold text-white">{n}</span><div><h3 className="font-bold">{t}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{c}</p></div></div>)}</div></div><div className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-100 p-3"><img src="https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1100&q=85" alt="Students in a classroom" className="h-[480px] w-full rounded-[1.5rem] object-cover"/><div className="absolute bottom-8 left-8 rounded-2xl border border-white/60 bg-white/95 p-5 shadow-xl"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><ShieldCheck size={20}/></div><div><p className="text-sm font-bold">Institution data boundary</p><p className="mt-1 text-xs text-slate-500">Each organization stays isolated.</p></div></div></div></div></div></div></section>

<section id="security" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="overflow-hidden rounded-[2rem] bg-slate-950 px-7 py-12 text-white sm:px-12 sm:py-16"><div className="grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-300">Built for multi-institution SaaS</p><h2 className="mt-4 max-w-2xl text-3xl font-bold tracking-tight sm:text-5xl">One platform. Many institutions. Separate workspaces.</h2><p className="mt-6 max-w-xl text-sm leading-7 text-slate-400">EduTechLab is designed so every school, coaching institute or madrasa gets its own users, data and permissions — while the platform owner can manage the wider ecosystem.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Organization-level data isolation","Admin & staff roles","Granular feature permissions","Ready for future integrations"].map(x=><div key={x} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-200"><Check size={16} className="text-blue-300"/>{x}</div>)}</div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-500/15 text-blue-300"><ShieldCheck size={22}/></div><div><p className="font-bold">Secure foundation</p><p className="text-xs text-slate-400">Designed around authenticated access</p></div></div><div className="mt-6 space-y-3">{["Students & admissions","Finance & receipts","Exams & results","Staff & permissions"].map(x=><div key={x} className="flex items-center justify-between rounded-xl bg-black/20 px-4 py-3 text-sm"><span>{x}</span><span className="text-xs font-semibold text-emerald-300">Protected</span></div>)}</div></div></div></div></section>

<section className="px-5 pb-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-blue-600 px-7 py-12 text-white sm:px-12 sm:py-14"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-100">Ready to start</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Bring your institution online.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-blue-100">Create your institution workspace and start building your education operations in one place.</p></div><Link href="/register" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-bold text-slate-950">Register your institute <ArrowRight size={16}/></Link></div></div></section>

<footer className="border-t border-slate-200 bg-white px-5 py-8 sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-xs text-slate-400 sm:flex-row"><span>© 2026 EduTechLab. Education, connected.</span><div className="flex gap-5"><Link href="/login" className="hover:text-slate-900">Login</Link><Link href="/register" className="hover:text-slate-900">Register</Link></div></div></footer>
</main>
}