"use client";
import Link from "next/link";
import { ArrowUpRight, Check, GraduationCap, Users, WalletCards, ClipboardCheck, MessageCircle, ShieldCheck, BarChart3, Sparkles, ChevronRight } from "lucide-react";

const modules = [
  ["01","Admissions","Turn enquiries into organized admissions with student records, classes and sections.",GraduationCap],
  ["02","Attendance","Daily attendance, class views and reports without paper registers.",ClipboardCheck],
  ["03","Finance","Fees, dues, collections and receipts in one clean financial workflow.",WalletCards],
  ["04","Examinations","Exams, marks, results and academic records built into the same system.",BarChart3],
  ["05","People & access","Staff accounts, roles and precise feature-level permissions.",Users],
  ["06","Parent connect","Notices and important student updates reach families from one place.",MessageCircle],
];

export default function Home(){
return <main className="min-h-screen overflow-hidden bg-[#f5f7fb] text-[#111827] selection:bg-indigo-200">
<div className="relative bg-[#07111f] text-white">
<div className="absolute inset-0 opacity-80 [background-image:radial-gradient(circle_at_20%_20%,rgba(99,102,241,.34),transparent_28%),radial-gradient(circle_at_80%_10%,rgba(34,211,238,.20),transparent_25%),radial-gradient(circle_at_70%_75%,rgba(168,85,247,.20),transparent_30%)]"/>
<div className="absolute inset-0 opacity-[.06] [background-image:linear-gradient(rgba(255,255,255,.8)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.8)_1px,transparent_1px)] [background-size:56px_56px]"/>
<header className="relative z-20 mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 sm:px-8 lg:px-12">
<Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[13px] border border-white/15 bg-white/10 shadow-[0_10px_40px_rgba(0,0,0,.25)] backdrop-blur"><GraduationCap size={20}/></span><span className="text-[19px] font-bold tracking-[-.03em]">EduTech<span className="text-cyan-300">Lab</span></span></Link>
<nav className="hidden items-center gap-9 text-[13px] font-medium text-white/55 md:flex"><a href="#platform" className="hover:text-white">Platform</a><a href="#features" className="hover:text-white">Solutions</a><a href="#security" className="hover:text-white">Security</a><a href="#workflow" className="hover:text-white">How it works</a></nav>
<div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-full px-4 py-2.5 text-sm text-white/70 hover:bg-white/8 hover:text-white sm:inline-flex">Sign in</Link><Link href="/register" className="group inline-flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-sm font-bold text-slate-950 shadow-[0_8px_35px_rgba(255,255,255,.14)] transition hover:-translate-y-0.5">Get started <ArrowUpRight size={15} className="transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></Link></div>
</header>

<section id="platform" className="relative mx-auto max-w-[1440px] px-5 pb-20 pt-14 sm:px-8 sm:pt-20 lg:px-12 lg:pb-28 lg:pt-24">
<div className="grid items-center gap-16 lg:grid-cols-[.88fr_1.12fr]">
<div className="relative z-10">
<div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-3.5 py-2 text-[11px] font-bold uppercase tracking-[.16em] text-cyan-100/85 backdrop-blur-xl"><Sparkles size={13} className="text-cyan-300"/> Education management, reimagined</div>
<h1 className="max-w-3xl text-[52px] font-semibold leading-[.94] tracking-[-.065em] sm:text-[68px] lg:text-[86px]">The operating system for <span className="bg-gradient-to-r from-cyan-200 via-white to-indigo-300 bg-clip-text text-transparent">modern education.</span></h1>
<p className="mt-8 max-w-xl text-[16px] leading-7 text-white/55 sm:text-lg">One beautifully connected workspace for schools, coaching institutes and madrasas — from the first admission to the final result.</p>
<div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="group inline-flex items-center justify-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-slate-950 shadow-[0_14px_50px_rgba(255,255,255,.12)] transition hover:-translate-y-1">Create your institution <ArrowUpRight size={17} className="transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></Link><a href="#features" className="inline-flex items-center justify-center rounded-full border border-white/12 bg-white/5 px-6 py-3.5 text-sm font-semibold text-white/80 backdrop-blur hover:bg-white/10">Explore the platform</a></div>
<div className="mt-9 flex flex-wrap gap-x-7 gap-y-3 text-[11px] font-medium text-white/40"><span className="flex items-center gap-2"><Check size={14} className="text-cyan-300"/> Multi-institution architecture</span><span className="flex items-center gap-2"><Check size={14} className="text-cyan-300"/> Granular permissions</span><span className="flex items-center gap-2"><Check size={14} className="text-cyan-300"/> Built to scale</span></div>
</div>

<div className="relative mx-auto w-full max-w-[720px] lg:ml-auto">
<div className="absolute -inset-10 rounded-full bg-indigo-500/20 blur-[90px]"/>
<div className="relative [perspective:1600px]">
<div className="absolute -right-5 -top-7 z-20 hidden w-48 rounded-2xl border border-white/15 bg-white/[.09] p-4 shadow-2xl backdrop-blur-2xl sm:block [transform:rotate(6deg)]">
<p className="text-[9px] uppercase tracking-[.18em] text-white/40">Today</p><p className="mt-1 text-2xl font-semibold">94.2%</p><p className="mt-1 text-[10px] text-emerald-300">Attendance rate</p>
</div>
<div className="absolute -bottom-7 -left-5 z-20 hidden w-52 rounded-2xl border border-white/15 bg-[#101d30]/90 p-4 shadow-2xl backdrop-blur-2xl sm:block [transform:rotate(-5deg)]">
<div className="flex items-center justify-between"><p className="text-[9px] uppercase tracking-[.18em] text-white/40">Fee collection</p><WalletCards size={14} className="text-cyan-300"/></div><p className="mt-1 text-2xl font-semibold">₹2.84L</p><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full w-[78%] rounded-full bg-gradient-to-r from-cyan-300 to-indigo-400"/></div>
</div>
<div className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-white/10 p-2 shadow-[0_40px_100px_rgba(0,0,0,.45)] backdrop-blur [transform:rotateX(5deg) rotateY(-7deg) rotateZ(1deg)]">
<div className="overflow-hidden rounded-[1.6rem] border border-white/10 bg-[#f6f8fc]">
<div className="flex h-10 items-center gap-1.5 border-b border-slate-200 bg-white px-4"><i className="h-2.5 w-2.5 rounded-full bg-slate-200"/><i className="h-2.5 w-2.5 rounded-full bg-slate-200"/><i className="h-2.5 w-2.5 rounded-full bg-slate-200"/><div className="mx-auto h-2 w-28 rounded-full bg-slate-100"/></div>
<div className="grid min-h-[390px] grid-cols-[72px_1fr] sm:min-h-[470px] sm:grid-cols-[100px_1fr]">
<aside className="border-r border-slate-200 bg-white p-3"><div className="mb-8 grid h-8 w-8 place-items-center rounded-lg bg-slate-950 text-white"><GraduationCap size={15}/></div>{[1,2,3,4,5,6].map((x)=><div key={x} className={`mb-5 h-2 rounded-full ${x===1?"w-12 bg-indigo-500":"w-8 bg-slate-100"}`}/>)}</aside>
<div className="p-4 sm:p-6"><div className="flex items-end justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">Institution overview</p><h3 className="mt-1 text-lg font-bold text-slate-900 sm:text-xl">Good morning, Admin</h3></div><div className="rounded-lg bg-indigo-600 px-3 py-2 text-[9px] font-bold text-white">+ Add</div></div>
<div className="mt-5 grid grid-cols-3 gap-2 sm:gap-3">{[["Students","428"],["Attendance","94.2%"],["Dues","₹64.5K"]].map(([a,b])=><div key={a} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><p className="text-[8px] text-slate-400">{a}</p><p className="mt-1 text-base font-bold text-slate-900">{b}</p><div className="mt-2 h-1 rounded-full bg-slate-100"><div className="h-full w-2/3 rounded-full bg-indigo-500"/></div></div>)}</div>
<div className="mt-3 grid grid-cols-[1.4fr_.6fr] gap-3"><div className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex justify-between"><span className="text-[8px] font-semibold text-slate-400">Attendance overview</span><span className="text-[8px] text-emerald-600">+2.1%</span></div><div className="mt-5 flex h-28 items-end gap-1">{[35,45,39,58,52,70,64,76,69,87,79,94].map((h,i)=><span key={i} className="flex-1 rounded-t bg-gradient-to-t from-indigo-600 to-cyan-300" style={{height:h+"%"}}/>)}</div></div><div className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><span className="text-[8px] font-semibold text-slate-400">Quick actions</span><div className="mt-4 space-y-2">{["Admission","Receipt","Notice"].map(x=><div key={x} className="rounded-lg bg-slate-50 px-2 py-2 text-[8px] font-semibold text-slate-600">{x}</div>)}</div></div></div>
</div></div></div></div>
</div></div></div></section>
</div>

<section id="features" className="relative mx-auto max-w-[1440px] px-5 py-24 sm:px-8 lg:px-12">
<div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.22em] text-indigo-600">One intelligent workspace</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Everything your institution needs, <span className="text-slate-400">without the clutter.</span></h2></div><p className="max-w-md text-sm leading-7 text-slate-500">Designed for real education teams — fast enough for daily work, structured enough for a growing institution.</p></div>
<div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-3">{modules.map(([num,title,copy,Icon])=><div key={title as string} className="group bg-white p-7 sm:p-9"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-950 text-white shadow-lg shadow-slate-900/10"><Icon size={20}/></div><span className="text-[10px] font-bold tracking-[.2em] text-slate-300">{num as string}</span></div><h3 className="mt-10 text-xl font-semibold tracking-tight">{title as string}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-slate-500">{copy as string}</p><div className="mt-8 flex items-center gap-2 text-xs font-bold text-indigo-600"><span className="h-px w-7 bg-indigo-200 transition-all group-hover:w-12"/><span>Built in</span></div></div>)}</div>
</section>

<section id="workflow" className="border-y border-slate-200 bg-[#edf1f7] py-24 sm:py-28">
<div className="mx-auto grid max-w-[1440px] gap-16 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-12 lg:items-center">
<div><p className="text-[11px] font-bold uppercase tracking-[.22em] text-indigo-600">A workspace for every institution</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">One platform. <span className="text-slate-400">Your rules.</span></h2><p className="mt-6 max-w-xl text-base leading-7 text-slate-500">Every school, coaching institute and madrasa gets its own isolated workspace. The owner becomes Admin and can create staff with exactly the access they need.</p><div className="mt-9 space-y-5">{[["01","Register","Create your institution and owner account."],["02","Configure","Set sessions, classes, sections, staff and permissions."],["03","Operate","Run admissions, attendance, fees, exams and communication."]].map(([n,t,c])=><div key={n} className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-white text-xs font-bold shadow-sm">{n}</span><div><p className="font-bold">{t}</p><p className="mt-1 text-sm text-slate-500">{c}</p></div></div>)}</div></div>
<div className="relative"><div className="absolute -inset-5 rounded-[3rem] bg-indigo-200/50 blur-3xl"/><div className="relative overflow-hidden rounded-[2rem] border border-white bg-white p-2 shadow-[0_30px_80px_rgba(15,23,42,.12)]"><img src="https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1400&q=90" alt="Modern education campus" className="h-[520px] w-full rounded-[1.6rem] object-cover"/><div className="absolute bottom-8 left-8 right-8 rounded-2xl border border-white/70 bg-white/90 p-5 shadow-xl backdrop-blur"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><ShieldCheck size={20}/></div><div><p className="font-bold">Private by architecture</p><p className="mt-1 text-xs text-slate-500">Institution data remains inside its own workspace.</p></div></div></div></div></div>
</div></section>

<section id="security" className="relative overflow-hidden bg-[#07111f] py-24 text-white sm:py-28">
<div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_50%,rgba(99,102,241,.25),transparent_35%),radial-gradient(circle_at_20%_0%,rgba(34,211,238,.13),transparent_25%)]"/>
<div className="relative mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="grid gap-14 lg:grid-cols-[1fr_.75fr] lg:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[.22em] text-cyan-300">The foundation</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Built for a world where <span className="text-white/35">education is connected.</span></h2><p className="mt-6 max-w-xl text-base leading-7 text-white/50">Secure authentication, organization-level data boundaries and granular permissions form the base. Integrations can be added as your platform grows.</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{["Separate institution workspaces","Admin, teacher & staff roles","Feature-level permissions","Ready for WhatsApp & payments"].map(x=><div key={x} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.05] px-4 py-3 text-sm text-white/75"><Check size={16} className="text-cyan-300"/>{x}</div>)}</div></div><div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-8 rounded-full bg-indigo-500/20 blur-[70px]"/><div className="relative rounded-[2rem] border border-white/10 bg-white/[.06] p-6 backdrop-blur-xl"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.2em] text-white/35">Workspace boundary</p><p className="mt-2 text-xl font-semibold">Institution A</p></div><ShieldCheck className="text-cyan-300"/></div><div className="mt-7 space-y-2">{["Students & admissions","Attendance & academics","Finance & receipts","Staff & permissions"].map(x=><div key={x} className="flex items-center justify-between rounded-xl border border-white/8 bg-black/10 px-4 py-3 text-xs text-white/65"><span>{x}</span><span className="text-[10px] text-emerald-300">Protected</span></div>)}</div></div></div></div></div>
</section>

<section className="px-5 py-20 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1440px] overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-indigo-600 via-indigo-600 to-cyan-500 p-[1px] shadow-[0_25px_80px_rgba(79,70,229,.2)]"><div className="rounded-[2.45rem] bg-gradient-to-br from-indigo-600 via-indigo-600 to-cyan-500 px-7 py-14 text-white sm:px-12 sm:py-16"><div className="flex flex-col justify-between gap-9 md:flex-row md:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[.22em] text-white/65">Ready for the next chapter?</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Make your institution feel effortless.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/70">Create your workspace and build your education operations around one modern system.</p></div><Link href="/register" className="group inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-slate-950">Register your institute <ArrowUpRight size={16} className="transition group-hover:translate-x-1 group-hover:-translate-y-1"/></Link></div></div></div></section>

<footer className="border-t border-slate-200 bg-white px-5 py-9 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-4 text-xs text-slate-400 sm:flex-row"><span>© 2026 EduTechLab · Education, connected.</span><div className="flex gap-6"><Link href="/login" className="hover:text-slate-900">Sign in</Link><Link href="/register" className="hover:text-slate-900">Register</Link></div></div></footer>
</main>
}