"use client"

import { FormEvent, useState } from "react"
import { createClient } from "@/lib/supabase/client"

export default function RegisterPage() {
  const supabase = createClient()
  const [step, setStep] = useState(1)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [form, setForm] = useState({name:"",type:"school",address:"",phone:"",email:"",adminName:"",adminEmail:"",password:""})
  const update=(key:string,value:string)=>setForm(f=>({...f,[key]:value}))
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const {data,error}=await supabase.auth.signUp({email:form.adminEmail,password:form.password,options:{data:{full_name:form.adminName}}});if(error){setError(error.message);setLoading(false);return} if(!data.user){setError("Registration could not be completed.");setLoading(false);return} const slug=form.name.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+"-"+Math.random().toString(36).slice(2,7); const {data:org,error:orgError}=await supabase.from("organizations").insert({name:form.name,slug}).select("id").single(); if(orgError){setError(orgError.message);setLoading(false);return} const {error:profileError}=await supabase.from("profiles").insert({id:data.user.id,organization_id:org.id,full_name:form.adminName,role:"owner"}); if(profileError){setError(profileError.message);setLoading(false);return} await supabase.from("organization_settings").insert({organization_id:org.id,institute_type:form.type,phone:form.phone,email:form.email,address:form.address}); window.location.href="/";}
  return <main className="min-h-screen bg-slate-50 px-6 py-10"><div className="mx-auto max-w-2xl rounded-3xl border border-slate-200 bg-white p-8 shadow-sm"><div className="mb-8"><p className="text-sm font-semibold text-slate-500">EduTechLab</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Register your institute</h1><p className="mt-2 text-slate-500">Create a dedicated management workspace for your school, madrasa or coaching institute.</p></div><div className="mb-8 flex gap-2">{[1,2,3].map(n=><div key={n} className={`h-2 flex-1 rounded-full ${step>=n?"bg-slate-900":"bg-slate-200"}`}/>)}</div><form onSubmit={submit} className="space-y-5">{step===1&&<><Field label="Institute name" value={form.name} onChange={v=>update("name",v)} required/><label className="block text-sm font-medium text-slate-700">Institute type<select className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" value={form.type} onChange={e=>update("type",e.target.value)}><option value="school">School</option><option value="coaching">Coaching Institute</option><option value="madrasa">Madrasa</option><option value="other">Other</option></select></label><Field label="Address" value={form.address} onChange={v=>update("address",v)}/><Field label="Institute phone" value={form.phone} onChange={v=>update("phone",v)}/><Field label="Institute email" value={form.email} onChange={v=>update("email",v)} type="email"/></>}{step===2&&<><Field label="Owner / Admin name" value={form.adminName} onChange={v=>update("adminName",v)} required/><Field label="Admin email" value={form.adminEmail} onChange={v=>update("adminEmail",v)} type="email" required/><Field label="Password" value={form.password} onChange={v=>update("password",v)} type="password" required/></>}{step===3&&<div className="rounded-2xl bg-slate-50 p-5"><h2 className="font-semibold text-slate-900">Ready to create your workspace</h2><p className="mt-2 text-sm text-slate-600">{form.name} will become your institute workspace and {form.adminName} will be the owner account.</p></div>} {error&&<p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="flex justify-between gap-3">{step>1?<button type="button" onClick={()=>setStep(s=>s-1)} className="rounded-xl border px-5 py-3">Back</button>:<span/>}{step<3?<button type="button" onClick={()=>setStep(s=>s+1)} className="rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white">Continue</button>:<button disabled={loading} className="rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-50">{loading?"Creating...":"Create institute"}</button>}</div></form></div></main>}
function Field({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label className="block text-sm font-medium text-slate-700">{label}<input className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" type={type} required={required} value={value} onChange={e=>onChange(e.target.value)}/></label>}
