"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,Printer} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
type S={id:string;first_name:string;last_name:string|null;admission_no:string;father_name:string|null;guardian_name:string|null};
type Sub={subject:string;max_marks:number;pass_percentage:number;sort_order:number};
type Mark={student_id:string;subject:string;marks:number|null;pass_percentage:number;status:"marked"|"absent"|"fail"|"pass"};
const fmt=(v:string|null)=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})};
const grade=(p:number)=>p>=90?"A+":p>=80?"A":p>=70?"B+":p>=60?"B":p>=50?"C":p>=33?"D":"F";
const initials=(n:string)=>n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
export default function AllMarksheets({params}:{params:Promise<{examId:string}>}){
 const supabase=createClient();const[exam,setExam]=useState<any>();const[org,setOrg]=useState<any>();const[settings,setSettings]=useState<any>();const[students,setStudents]=useState<S[]>([]);const[subs,setSubs]=useState<Sub[]>([]);const[marks,setMarks]=useState<Mark[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const{examId}=await params;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:p}=await supabase.from("profiles").select("organization_id").eq("id",user.id).single();if(!p)return;
 const[a,b,c,d,e]=await Promise.all([supabase.from("exams").select("id,name,exam_date").eq("id",examId).eq("organization_id",p.organization_id).single(),supabase.from("organizations").select("name").eq("id",p.organization_id).single(),supabase.from("organization_settings").select("address,phone,email,authorized_signatory,primary_color,secondary_color,marksheet_title").eq("organization_id",p.organization_id).single(),supabase.from("exam_subjects").select("subject,max_marks,pass_percentage,sort_order").eq("exam_id",examId).eq("organization_id",p.organization_id).order("sort_order"),supabase.from("exam_marks").select("student_id,subject,marks,pass_percentage,status").eq("exam_id",examId).eq("organization_id",p.organization_id)]);
 const{data:st}=await supabase.from("students").select("id,first_name,last_name,admission_no,father_name,guardian_name").eq("organization_id",p.organization_id).eq("status","active").order("first_name");setExam(a.data);setOrg(b.data);setSettings(c.data);setSubs((d.data||[])as Sub[]);setStudents((st||[])as S[]);setMarks((e.data||[])as Mark[]);setLoading(false)})()},[params]);
 if(loading)return <main className="grid min-h-screen place-items-center bg-slate-100 text-slate-500">Preparing marksheets…</main>;
 const primary=settings?.primary_color||"#0e4b43",accent=settings?.secondary_color||"#c5a15a";const map:Record<string,Record<string,Mark>>={};marks.forEach(m=>(map[m.student_id]||={})[m.subject]=m);
 return <main className="min-h-screen bg-[#e9ece8] p-2 sm:p-5"><div className="no-print mx-auto mb-4 flex max-w-[794px] justify-between"><button onClick={()=>history.back()} className="rounded-lg border bg-white px-3 py-2 text-sm"><ArrowLeft size={16} className="mr-1 inline"/>Back</button><button onClick={()=>print()} className="rounded-lg px-4 py-2 text-sm font-semibold text-white" style={{backgroundColor:primary}}><Printer size={16} className="mr-1 inline"/>Print / Save All PDF</button></div>
 <div className="mx-auto max-w-[794px]">{students.map((st,idx)=>{const rows=subs.map(s=>{const m=map[st.id]?.[s.subject];return{...s,marks:m?.marks??null,status:m?.status||"absent"} as any});const total=rows.reduce((n,r)=>n+Number(r.marks??0),0),max=rows.reduce((n,r)=>n+Number(r.max_marks),0),pct=max?total/max*100:0;const passed=rows.length>0&&rows.every(r=>r.status!=="absent"&&r.status!=="fail"&&(r.marks==null&&r.status==="pass"||r.marks!=null&&Number(r.marks)/Number(r.max_marks)*100>=Number(r.pass_percentage??30)));
 return <article className="marksheet relative mb-5 min-h-[1123px] w-full max-w-[794px] overflow-hidden bg-[#fbfaf6] text-[#202522] shadow-[0_18px_60px_rgba(0,0,0,.16)]" key={st.id}><div className="absolute inset-y-0 left-0 w-1.5" style={{backgroundColor:accent}}/><div className="absolute inset-y-0 right-0 w-1.5" style={{backgroundColor:accent}}/><div className="relative px-7 py-7 sm:px-10 sm:py-8">
 <header className="relative overflow-hidden border-b-[3px] pb-5" style={{borderColor:accent}}><p className="text-[8px] font-bold uppercase tracking-[.35em]" style={{color:accent}}>Academic Examination</p><h1 className="mt-2 text-[26px] font-black uppercase leading-none tracking-[0.035em] sm:text-[31px]" style={{color:primary}}>{org?.name||"Institution Name"}</h1><p className="mt-1 text-[10px] font-semibold uppercase tracking-widest text-slate-500">Official Academic Record</p><p className="mt-2 text-[9px] text-slate-500">{[settings?.address,settings?.phone,settings?.email].filter(Boolean).join(" • ")}</p><h2 className="mt-5 text-[21px] font-black uppercase" style={{color:primary}}>{settings?.marksheet_title||"Statement of Marks"}</h2><p className="text-[11px] font-semibold text-slate-500">{exam?.name} • {fmt(exam?.exam_date)}</p></header>
 <section className="mt-5 rounded-xl border bg-white/70 p-4"><div className="grid grid-cols-4 gap-3"><Info l="Student Name" v={[st.first_name,st.last_name].filter(Boolean).join(" ")} b/><Info l="Admission No." v={st.admission_no}/><Info l="Father / Guardian" v={st.father_name||st.guardian_name}/><Info l="Exam Date" v={fmt(exam?.exam_date)}/></div></section>
 <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[0.32em]" style={{color:accent}}>Academic Performance</p><h3 className="mt-1 text-[17px] font-black uppercase tracking-wide" style={{color:primary}}>Subject-wise Assessment</h3><span className="text-[10px] font-semibold text-slate-400">{rows.length} {rows.length===1?"Subject":"Subjects"}</span></div></div><table className="w-full border-collapse text-[10px]"><thead><tr style={{backgroundColor:primary,color:"#fff"}}><th className="p-2">S.No.</th><th className="p-2 text-left">Subject</th><th className="p-2">Maximum</th><th className="p-2">Obtained</th><th className="p-2">Grade</th><th className="p-2">Status</th></tr></thead><tbody>{rows.map((r,i)=>{const pct=r.max_marks?Number(r.marks??0)/Number(r.max_marks)*100:0;const status=r.marks==null?r.status.toUpperCase():(pct>=Number(r.pass_percentage??30)?"PASS":"FAIL");return <tr key={r.subject} className={i%2?"bg-white":"bg-[#f4f4ee]"}><td className="border-b p-2 text-center">{i+1}</td><td className="border-b p-2 font-semibold">{r.subject}</td><td className="border-b p-2 text-center">{r.max_marks}</td><td className="border-b p-2 text-center font-black">{r.marks==null?status:r.marks}</td><td className="border-b p-2 text-center font-black" style={{color:primary}}>{r.marks==null?(r.status==="pass"?"P":r.status==="absent"?"AB":r.status==="fail"?"F":"—"):grade(pct)}</td><td className="border-b p-2 text-center text-[9px] font-bold">{status}</td></tr>})}<tr style={{backgroundColor:accent+"33"}}><td colSpan={2} className="p-2.5 text-right font-black">GRAND TOTAL</td><td className="p-2.5 text-center font-black">{max}</td><td className="p-2.5 text-center font-black" style={{color:primary}}>{total}</td><td colSpan={2} className="p-2.5 text-center font-black" style={{color:primary}}>{grade(pct)}</td></tr></tbody></table></section>
 <section className="mt-6 grid grid-cols-3 rounded-xl border bg-white/70"><Stat l="Percentage" v={pct.toFixed(2)+"%"}/><Stat l="Overall Grade" v={grade(pct)}/><Stat l="Final Result" v={passed?"✓ PASS":"✕ FAIL"}/></section>
 <section className="mt-12 grid grid-cols-3 gap-5"><Sign t="Class Teacher"/><div className="text-center pt-8"><div className="mx-auto h-12 w-12 rounded-full border-2 border-dashed" style={{borderColor:accent}}/><p className="mt-2 border-t pt-2 text-[8px] font-bold uppercase text-slate-500">Institution Seal</p></div><Sign t={settings?.authorized_signatory||"Authorized Signatory"}/></section>
 <footer className="mt-8 border-t pt-3 text-center text-[8px] text-slate-400">This is an official academic record issued by {org?.name||"the institution"} • EduTechLab</footer></div><div className="pointer-events-none absolute bottom-0 left-0 h-10 w-full" style={{background:"linear-gradient(90deg,"+primary+","+accent+","+primary+")"}}/></article>})}</div>
 <style jsx global>{'@media print{html,body{background:#fff!important}.no-print{display:none!important}.marksheet{width:210mm!important;height:297mm!important;min-height:297mm!important;max-height:297mm!important;margin:0!important;box-shadow:none!important;break-after:page;page-break-after:always}.marksheet:last-child{break-after:auto;page-break-after:auto}@page{size:A4;margin:0}*{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}}'}</style></main>;
}
function Info({l,v,b=false}:{l:string;v?:string|null;b?:boolean}){return <div><p className="text-[7px] font-bold uppercase tracking-wider text-slate-400">{l}</p><p className={"mt-0.5 truncate text-[9px] "+(b?"font-black":"font-semibold")}>{v||"—"}</p></div>}
function Stat({l,v}:{l:string;v:string}){return <div className="border-r p-3 text-center last:border-0"><p className="text-[7px] font-black uppercase tracking-widest text-slate-400">{l}</p><p className="mt-1 text-[17px] font-black" style={{color:"var(--primary)"}}>{v}</p></div>}
function Sign({t}:{t:string}){return <div className="pt-8 text-center"><div className="border-t border-slate-400"/><p className="mt-2 text-[8px] font-bold uppercase text-slate-500">{t}</p><p className="text-[7px] text-slate-400">Signature & Date</p></div>}
