"use client";

import { useEffect, useMemo, useState } from "react";
import { Plus, Search, Trash2, X, Pencil, ArrowLeft } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Student = {  id:string; admission_no:string; first_name:string; last_name:string|null; phone:string|null; email:string|null; status:string ; father_name:string|null; mother_name:string|null; guardian_name:string|null; guardian_phone:string|null; aadhaar_number:string|null; photo_url:string|null; aadhaar_document_url:string|null; birth_certificate_url:string|null; address:string|null; date_of_birth:string|null; gender:string|null };
export default function Students(){
 const supabase=createClient(); const [org,setOrg]=useState(""); const [rows,setRows]=useState<Student[]>([]); const [q,setQ]=useState(""); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Student|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const [form,setForm]=useState({admission_no:"",first_name:"",last_name:"",phone:"",email:"",status:"active",father_name:"",mother_name:"",guardian_name:"",guardian_phone:"",aadhaar_number:"",photo_url:"",aadhaar_document_url:"",birth_certificate_url:"",address:"",date_of_birth:"",gender:""});
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const {data:p}=await supabase.from("profiles").select("organization_id").eq("id",user.id).single(); if(!p)return; setOrg(p.organization_id); const {data,error}=await supabase.from("students").select("id,admission_no,first_name,last_name,phone,email,status,father_name,mother_name,guardian_name,guardian_phone,aadhaar_number,photo_url,aadhaar_document_url,birth_certificate_url,address,date_of_birth,gender").eq("organization_id",p.organization_id).order("created_at",{ascending:false}); if(error)setError(error.message); else setRows(data||[]);};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(r.first_name+" "+(r.last_name||"")+" "+r.admission_no).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const reset=()=>{setForm({admission_no:"",first_name:"",last_name:"",phone:"",email:"",status:"active",father_name:"",mother_name:"",guardian_name:"",guardian_phone:"",aadhaar_number:"",photo_url:"",aadhaar_document_url:"",birth_certificate_url:"",address:"",date_of_birth:"",gender:""});setEditing(null);setOpen(false);setError("")};
 const save=async()=>{setSaving(true);setError(""); const payload={organization_id:org,...form,last_name:form.last_name||null,phone:form.phone||null,email:form.email||null,father_name:form.father_name||null,mother_name:form.mother_name||null,guardian_name:form.guardian_name||null,guardian_phone:form.guardian_phone||null,aadhaar_number:form.aadhaar_number||null,photo_url:form.photo_url||null,aadhaar_document_url:form.aadhaar_document_url||null,birth_certificate_url:form.birth_certificate_url||null,address:form.address||null,date_of_birth:form.date_of_birth||null,gender:form.gender||null}; const res=editing?await supabase.from("students").update(payload).eq("id",editing.id):await supabase.from("students").insert(payload); if(res.error)setError(res.error.message);else{reset();await load()}setSaving(false)};
 const del=async(id:string)=>{if(!confirm("Delete this student and linked records?"))return; const {error}=await supabase.from("students").delete().eq("id",id); if(error)setError(error.message);else await load()};
 return <main className="mx-auto max-w-7xl p-5 sm:p-8"><button onClick={()=>window.history.back()} className="mb-5 inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm text-slate-600 hover:bg-slate-50"><ArrowLeft size={16}/>Back</button><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-slate-500">EduTechLab / Students</p><h1 className="mt-1 text-3xl font-bold">Students</h1><p className="mt-2 text-sm text-slate-500">Live student records for your institute.</p></div><button onClick={()=>{setEditing(null);setOpen(true)}} className="flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17}/>Add student</button></div>
 <div className="mt-7 flex items-center gap-3 rounded-xl border bg-white px-3 py-2.5"><Search size={18} className="text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by name or admission number" className="w-full bg-transparent text-sm outline-none"/></div>
 {error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="mt-5 overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4 font-semibold">Student directory <span className="ml-2 text-xs font-normal text-slate-400">{filtered.length}</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">Admission</th><th className="px-5 py-3">Student</th><th className="px-5 py-3">Phone</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="px-5 py-4 font-medium">{r.admission_no}</td><td className="px-5 py-4">{r.first_name} {r.last_name||""}</td><td className="px-5 py-4 text-slate-600">{r.phone||"—"}</td><td className="px-5 py-4">{r.status}</td><td className="px-5 py-4 text-right"><button onClick={()=>{setEditing(r);setForm({admission_no:r.admission_no,first_name:r.first_name,last_name:r.last_name||"",phone:r.phone||"",email:r.email||"",status:r.status,father_name:r.father_name||"",mother_name:r.mother_name||"",guardian_name:r.guardian_name||"",guardian_phone:r.guardian_phone||"",aadhaar_number:r.aadhaar_number||"",photo_url:r.photo_url||"",aadhaar_document_url:r.aadhaar_document_url||"",birth_certificate_url:r.birth_certificate_url||"",address:r.address||"",date_of_birth:r.date_of_birth||"",gender:r.gender||""});setOpen(true)}} className="mr-3"><Pencil size={17}/></button><button onClick={()=>del(r.id)}><Trash2 size={17}/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-10 text-center text-sm text-slate-500">No students yet. Add the first student.</div>}</div></div>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing?"Edit":"Add"} student</h2><button onClick={reset}><X/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["admission_no","Admission no."],["first_name","First name"],["last_name","Last name"],["date_of_birth","Date of birth"],["phone","Phone"],["email","Email"],["father_name","Father name"],["mother_name","Mother name"],["guardian_name","Guardian name"],["guardian_phone","Guardian phone"],["aadhaar_number","Aadhaar number"],["photo_url","Student photo URL"],["aadhaar_document_url","Aadhaar document URL"],["birth_certificate_url","Birth certificate URL"],["address","Full address"]].map(([k,l])=><label key={k} className="text-sm">{l}<input value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5"/></label>)}<label className="text-sm">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2.5"><option value="active">Active</option><option value="inactive">Inactive</option><option value="alumni">Alumni</option></select></label></div><button disabled={saving} onClick={save} className="mt-5 w-full rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white">{saving?"Saving…":"Save student"}</button></div></div>}</main>
}