create extension if not exists pgcrypto;
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, created_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, organization_id uuid references public.organizations(id) on delete cascade, full_name text not null, role text not null check (role in ('owner','admin','teacher','staff','parent')), created_at timestamptz not null default now());
create table public.academic_sessions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, starts_on date not null, ends_on date not null, is_current boolean not null default false, created_at timestamptz not null default now());
create table public.classes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, sort_order int not null default 0, created_at timestamptz not null default now());
create table public.sections (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, class_id uuid not null references public.classes(id) on delete cascade, name text not null, created_at timestamptz not null default now());
create table public.students (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, admission_no text not null, first_name text not null, last_name text, date_of_birth date, gender text, phone text, email text, class_id uuid references public.classes(id) on delete set null, section_id uuid references public.sections(id) on delete set null, status text not null default 'active' check (status in ('active','inactive','alumni')), created_at timestamptz not null default now(), unique (organization_id, admission_no));
create table public.parents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, full_name text not null, phone text, email text, created_at timestamptz not null default now());
create table public.student_parents (student_id uuid not null references public.students(id) on delete cascade, parent_id uuid not null references public.parents(id) on delete cascade, relationship text, is_primary boolean not null default false, primary key (student_id,parent_id));
create table public.teachers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, full_name text not null, phone text, email text, created_at timestamptz not null default now());
create table public.attendance (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, attendance_date date not null, status text not null check (status in ('present','absent','late','leave')), note text, created_at timestamptz not null default now(), unique(student_id,attendance_date));
create table public.fee_payments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, amount numeric(12,2) not null check(amount>=0), paid_on date not null default current_date, method text not null default 'cash', reference text, note text, created_at timestamptz not null default now());
create table public.exams (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, exam_date date, created_at timestamptz not null default now());
create table public.exam_marks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, exam_id uuid not null references public.exams(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, subject text not null, marks numeric(7,2) not null default 0, max_marks numeric(7,2) not null default 100, created_at timestamptz not null default now(), unique(exam_id,student_id,subject));
create table public.notices (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, title text not null, body text not null, published_at timestamptz default now(), created_at timestamptz not null default now());
create index students_org_idx on public.students(organization_id);
create index attendance_org_date_idx on public.attendance(organization_id,attendance_date);
create index fee_payments_org_date_idx on public.fee_payments(organization_id,paid_on);
alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.academic_sessions enable row level security;
alter table public.classes enable row level security;
alter table public.sections enable row level security;
alter table public.students enable row level security;
alter table public.parents enable row level security;
alter table public.student_parents enable row level security;
alter table public.teachers enable row level security;
alter table public.attendance enable row level security;
alter table public.fee_payments enable row level security;
alter table public.exams enable row level security;
alter table public.exam_marks enable row level security;
alter table public.notices enable row level security;
create or replace function public.user_org_id() returns uuid language sql stable security definer set search_path=public as $$ select organization_id from public.profiles where id=auth.uid() $$;
create policy "org members read organization" on public.organizations for select using(id=public.user_org_id());
create policy "profiles same org" on public.profiles for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "sessions same org" on public.academic_sessions for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "classes same org" on public.classes for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "sections same org" on public.sections for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "students same org" on public.students for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "parents same org" on public.parents for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "student parents same org" on public.student_parents for all using(exists(select 1 from public.students s where s.id=student_id and s.organization_id=public.user_org_id())) with check(exists(select 1 from public.students s where s.id=student_id and s.organization_id=public.user_org_id()));
create policy "teachers same org" on public.teachers for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "attendance same org" on public.attendance for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "payments same org" on public.fee_payments for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "exams same org" on public.exams for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "marks same org" on public.exam_marks for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());
create policy "notices same org" on public.notices for all using(organization_id=public.user_org_id()) with check(organization_id=public.user_org_id());